spring:
  datasource:
    username: postgres
    password: imintcs3
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xpense_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
