spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true        # Automatically create routes for services in Eureka
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: account-service
          uri: lb://order-service
          predicates:
            - Path=/api/accounts/**

server:
  port: 8080


